// Diccionarios de traducción. Las claves son el texto ORIGINAL en español.
// Lo que no esté aquí se muestra en español (fallback). Los placeholders {x}
// se interpolan en runtime y se conservan igual en cada idioma.
export const DICT = {
  en: {
    " · {n} deshacer disponibles": " · {n} undo available",
    "(sin nombre)": "(no name)",
    "+ AÑADIR GRUPO": "+ ADD GROUP",
    "+ AÑADIR NOTA": "+ ADD NOTE",
    "+ Añadir RF": "+ Add RF",
    "+ Añadir artista": "+ Add artist",
    "+ Añadir día": "+ Add day",
    "+ Añadir fila": "+ Add row",
    "+ Añadir nota": "+ Add note",
    "+ Añadir stage": "+ Add stage",
    "+ CREAR FESTIVAL": "+ CREATE FESTIVAL",
    "+ Campo": "+ Field",
    "+ Nuevo campo": "+ New field",
    ". Esta acción no se puede deshacer.": ". This action cannot be undone.",
    "ARTISTA {n}": "ARTIST {n}",
    "ARTISTAS": "ARTISTS",
    "Activar avisos": "Enable alerts",
    "Android — Chrome": "Android — Chrome",
    "Archivo": "File",
    "Asegúrate de haber ejecutado el SQL en Supabase y de tener las tablas": "Make sure you have run the SQL in Supabase and have the tables",
    "Avisos": "Alerts",
    "AÑADIR AL PLANO": "ADD TO PLOT",
    "AÑADIR CONEXIÓN": "ADD CONNECTION",
    "AÑADIR ESCENARIO": "ADD STAGE",
    "AÑADIR FOH": "ADD FOH",
    "AÑADIR MONITORES": "ADD MONITORS",
    "Añadir": "Add",
    "Añadir a pantalla de inicio": "Add to Home Screen",
    "Añadir al Dock...": "Add to Dock...",
    "Añadir al día": "Add to day",
    "Añadir día": "Add day",
    "Añadir nota…": "Add note…",
    "Aún no hay miembros. Comparte un enlace para invitar.": "No members yet. Share a link to invite.",
    "BANDAS": "BANDS",
    "BORRAR": "DELETE",
    "Borrar": "Delete",
    "Borrar cuenta": "Delete account",
    "Borrar mi cuenta": "Delete my account",
    "Borrar mi cuenta y todos mis datos": "Delete my account and all my data",
    "Borrando…": "Deleting…",
    "CAMPOS EXTRA": "EXTRA FIELDS",
    "CANTIDAD": "QUANTITY",
    "CH desde": "CH from",
    "CH hasta": "CH to",
    "COMPARTIR": "SHARE",
    "CONEXIÓN": "CONNECTION",
    "COPIA": "COPY",
    "COPIADO": "COPIED",
    "COPIAR URL": "COPY URL",
    "CORRIENTE": "POWER",
    "CREAR GRUPO": "CREATE GROUP",
    "Campos extra": "Extra fields",
    "Campos extra (artista)": "Extra fields (artist)",
    "Cancelar": "Cancel",
    "Cerrar": "Close",
    "Cerrar sesión": "Sign out",
    "Colocar subbox": "Place subbox",
    "Compartir": "Share",
    "Conectando…": "Connecting…",
    "Conexiones": "Connections",
    "Conexión": "Connection",
    "Consola": "Console",
    "Consola MON": "MON console",
    "Continuar con Google": "Continue with Google",
    "Copiar": "Copy",
    "Copiar al día →": "Copy to day →",
    "Copiar artistas": "Copy artists",
    "Corriente": "Power",
    "Crear festival": "Create festival",
    "Créalos primero en la pestaña": "Create them first in the",
    "DE": "FROM",
    "DESCRIPCIÓN": "DESCRIPTION",
    "Desactivar avisos": "Disable alerts",
    "Descripción · {d}": "Description · {d}",
    "Deshacer": "Undo",
    "Dest": "Dest",
    "Duplicar grupo": "Duplicate group",
    "DÍA 1": "DAY 1",
    "DÍA {n}": "DAY {n}",
    "DÍAS": "DAYS",
    "DÍAS DESTINO": "TARGET DAYS",
    "EDITAR ARTISTA": "EDIT ARTIST",
    "EDITAR FESTIVAL": "EDIT FESTIVAL",
    "EDITAR GRUPO": "EDIT GROUP",
    "EDITAR RULO": "EDIT CABLE",
    "EDITOR": "EDITOR",
    "ESCENARIO": "STAGE",
    "ESCENARIO PRINCIPAL": "MAIN STAGE",
    "ETAPAS": "AMPS",
    "Editar": "Edit",
    "Editor": "Editor",
    "Ej: El sábado mover a Cultura Jaén SL": "e.g. On Saturday move to Cultura Jaén SL",
    "Ej: HMA OPTOCORE Festival Box": "e.g. HMA OPTOCORE Festival Box",
    "Ej: Mad Cool 26": "e.g. Mad Cool 26",
    "Ej: Mad Cool 27": "e.g. Mad Cool 27",
    "Eliminar": "Delete",
    "Eliminar posición de escenario": "Delete stage position",
    "Error al conectar con la base de datos": "Error connecting to the database",
    "Escenario": "Stage",
    "Escenario asignado": "Assigned stage",
    "Escribe una nota…": "Write a note…",
    "Escribe {word} para confirmar": "Type {word} to confirm",
    "Esta acción es permanente e irreversible.": "This action is permanent and irreversible.",
    "Este navegador no soporta notificaciones push, o falta configurar la clave VAPID.": "This browser does not support push notifications, or the VAPID key is not configured.",
    "Etiqueta": "Label",
    "Etiqueta (RF, Backline…)": "Label (RF, Backline…)",
    "Etiqueta (RF…)": "Label (RF…)",
    "Etiqueta personalizada (opcional)": "Custom label (optional)",
    "Exportar PDF": "Export PDF",
    "Exportar PDF del día": "Export day PDF",
    "Expulsar": "Remove",
    "FESTIVALES": "FESTIVALS",
    "FILAS · AMP — ID": "ROWS · AMP — ID",
    "FONDO · BACKLINE": "BACK · BACKLINE",
    "Ficha compacta": "Compact card",
    "Fila {r} · Col {c}": "Row {r} · Col {c}",
    "GRUPO VINCULADO": "LINKED GROUP",
    "GUARDAR CAMBIOS": "SAVE CHANGES",
    "GUARDAR FESTIVAL": "SAVE FESTIVAL",
    "Generado:": "Generated:",
    "General": "General",
    "Gestiona y sincroniza tus handovers de sonido en tiempo real con todo tu equipo.": "Manage and sync your sound handovers in real time with your whole team.",
    "Gestionar miembros": "Manage members",
    "Gestión de consola y artistas": "Console and artist management",
    "Global:": "Global:",
    "Grupo": "Group",
    "Guardar": "Save",
    "Guardar artista": "Save artist",
    "Guardar cambios": "Save changes",
    "HORARIOS": "SCHEDULE",
    "HORARIOS — {d} · {n} artistas": "SCHEDULE — {d} · {n} artists",
    "Hecho": "Done",
    "INSTALAR APP": "INSTALL APP",
    "Icono de instalación": "Install icon",
    "Idioma": "Language",
    "Inputs, corriente y plano": "Inputs, power and plot",
    "Instalar": "Install",
    "Instrumento": "Instrument",
    "Instálala desde el navegador y ábrela como una app más, directamente desde tu pantalla de inicio.": "Install it from the browser and open it like any other app, straight from your home screen.",
    "Instálala desde el navegador y ábrela en su propia ventana, sin pestañas ni barra de direcciones.": "Install it from the browser and open it in its own window, with no tabs or address bar.",
    "Mac — Safari": "Mac — Safari",
    "Menú": "Menu",
    "Mesa": "Console",
    "Mesa FOH": "FOH console",
    "Mic / DI": "Mic / DI",
    "NOMBRE": "NAME",
    "NOMBRE DE LA PLANTILLA": "TEMPLATE NAME",
    "NOMBRE DEL FESTIVAL": "FESTIVAL NAME",
    "NOMBRE DEL GRUPO": "GROUP NAME",
    "NOTA (opcional)": "NOTE (optional)",
    "NOTAS": "NOTES",
    "NOTAS DEL DÍA": "DAY NOTES",
    "NOTAS FOH (turno)": "FOH NOTES (shift)",
    "NOTAS PREVIAS": "PREVIOUS NOTES",
    "NUEVA POSICIÓN DE ESCENARIO": "NEW STAGE POSITION",
    "NUEVO ARTISTA": "NEW ARTIST",
    "NUEVO FESTIVAL": "NEW FESTIVAL",
    "NUEVO GRUPO": "NEW GROUP",
    "NUEVO RULO": "NEW CABLE",
    "Name": "Name",
    "No": "No",
    "No hay artistas en este día": "No artists on this day",
    "No hay grupos de corriente.": "No power groups.",
    "No se pudo actualizar la suscripción": "Could not update the subscription",
    "No se pudo borrar la cuenta": "Could not delete the account",
    "Nombre (ej. SB1)": "Name (e.g. SB1)",
    "Nombre / Fuente": "Name / Source",
    "Nombre artista": "Artist name",
    "Nombre artista *": "Artist name *",
    "Nombre del stage": "Stage name",
    "Nota para tu compañero…": "Note for your colleague…",
    "Notas": "Notes",
    "Notas FOH": "FOH notes",
    "Notas previas": "Previous notes",
    "Nueva posición de monitores": "New monitor position",
    "Otro": "Other",
    "Owner": "Owner",
    "PARA": "TO",
    "PLANO": "PLOT",
    "POSICIONES": "POSITIONS",
    "POSICIÓN EN ESCENARIO": "STAGE POSITION",
    "Parcheo FOH": "FOH patch",
    "Plantillas": "Templates",
    "Preset": "Preset",
    "Pulsa": "Tap",
    "PÚBLICO": "AUDIENCE",
    "RF — {n} unidades": "RF — {n} units",
    "RULOS": "CABLES",
    "Recibe notificaciones de los artistas del escenario en el que estés trabajando.": "Get notifications for the artists on the stage you're working on.",
    "Rulo permanente": "Permanent cable",
    "Rutas": "Routes",
    "SC FIN": "SC END",
    "SC INICIO": "SC START",
    "SH FIN": "SH END",
    "SH INICIO": "SH START",
    "SHOW FIN": "SHOW END",
    "SHOW INICIO": "SHOW START",
    "SIN CONEXIÓN — mostrando últimos datos guardados": "OFFLINE — showing last saved data",
    "SOUNDCHECK": "SOUNDCHECK",
    "STAGES": "STAGES",
    "Se borrarán para siempre:": "The following will be deleted forever:",
    "Se borrarán todos los inputs, grupos de corriente y el plano de {n}. Esta acción no se puede deshacer.": "All inputs, power groups and the plot of {n} will be deleted. This action cannot be undone.",
    "Selecciona los artistas a copiar y los días destino.": "Select the artists to copy and the target days.",
    "Setup monitor": "Monitor setup",
    "Setup técnico": "Technical setup",
    "Señal": "Signal",
    "Ningún artista tiene soundcheck asignado": "No artist has a soundcheck assigned",
    "Sin artistas en este día": "No artists on this day",
    "Sin confirmar": "Unconfirmed",
    "Sin descripción": "No description",
    "Sin días configurados": "No days set up",
    "Sin grupos de etapas": "No amp groups",
    "Sin inputs en este rango — defínelos en la pestaña INPUTS.": "No inputs in this range — define them in the INPUTS tab.",
    "Sin notas para este día": "No notes for this day",
    "Slots en directo": "Live slots",
    "Subbox": "Subbox",
    "Sí, borrar": "Yes, delete",
    "Sí, eliminar": "Yes, delete",
    "TIPO DE CABLE": "CABLE TYPE",
    "TUS": "YOUR",
    "Te invito a {n} como {r}": "I'm inviting you to {n} as {r}",
    "Tipo": "Type",
    "Todos los escenarios": "All stages",
    "Tomas": "Outlets",
    "Tomas {n}": "Outlets {n}",
    "Tus avisos de soundcheck se ajustarán a este escenario. Puedes cambiarlo cuando quieras.": "Your soundcheck alerts will match this stage. You can change it whenever you want.",
    "Tus festivales y todos sus datos": "Your festivals and all their data",
    "Tu pertenencia a festivales de otros": "Your membership in others' festivals",
    "Tus preferencias y avisos": "Your preferences and alerts",
    "Tu cuenta de acceso": "Your login account",
    "Type": "Type",
    "Técnico": "Engineer",
    "USAR PLANTILLA": "USE TEMPLATE",
    "Usar": "Use",
    "Usar global ↩": "Use global ↩",
    "User / artista": "User / artist",
    "Usuario {x}": "User {x}",
    "VISOR": "VIEWER",
    "Valor": "Value",
    "Vas a borrar": "You are about to delete",
    "Vincula un grupo de la pestaña CORRIENTE.": "Link a group from the POWER tab.",
    "Visible en todos los días del stage": "Visible on every day of the stage",
    "Visor": "Viewer",
    "Windows / Mac — Chrome": "Windows / Mac — Chrome",
    "a la derecha de la barra de direcciones": "to the right of the address bar",
    "arriba a la derecha": "top right",
    "cargando…": "loading…",
    "claro": "light",
    "consola mon": "mon console",
    "creadas.": "created.",
    "en la barra inferior": "in the bottom bar",
    "en la barra superior": "in the top bar",
    "este día": "this day",
    "iPhone / iPad — Safari": "iPhone / iPad — Safari",
    "mesa": "console",
    "oscuro": "dark",
    "preset?": "preset?",
    "sin confirmar": "unconfirmed",
    "sin entradas": "no entries",
    "técnico": "engineer",
    "y": "and",
    "{a} artistas · {d} días": "{a} artists · {d} days",
    "{d} días · {a} artistas": "{d} days · {a} artists",
    "{i} inputs · {p} grupos corriente": "{i} inputs · {p} power groups",
    "{n} INPUT(S) EN RANGO": "{n} INPUT(S) IN RANGE",
    "{n} art.": "{n} art.",
    "{n} artistas": "{n} artists",
    "{n} entradas · últimos 1000 cambios": "{n} entries · last 1000 changes",
    "{n} filas": "{n} rows",
    "{n} input(s) de la pestaña INPUTS en este rango": "{n} input(s) from the INPUTS tab in this range",
    "{n} tomas": "{n} outlets",
    "{s} stages · {a} artistas": "{s} stages · {a} artists",
    "¡ENTENDIDO!": "GOT IT!",
    "¿Borrar artista?": "Delete artist?",
    "¿Borrar esta conexión?": "Delete this connection?",
    "¿Borrar festival?": "Delete festival?",
    "¿Borrar plantilla?": "Delete template?",
    "¿Con qué acceso?": "With what access?",
    "¿Eliminar el grupo \"{n}\"?": "Delete the group \"{n}\"?",
    "¿Eliminar el stage \"{n}\"? Se perderán todos sus días y artistas.": "Delete the stage \"{n}\"? All its days and artists will be lost.",
    "¿Eliminar la posición \"{n}\"?": "Delete the position \"{n}\"?",
    "¿Eliminar la posición de escenario?": "Delete the stage position?",
    "¿Eliminar posición de monitores \"{n}\"?": "Delete the monitor position \"{n}\"?",
    "¿Eliminar todos los artistas de FOH en {n}?": "Delete all FOH artists in {n}?",
    "¿Eliminar {d}? Se perderán todos sus artistas.": "Delete {d}? All its artists will be lost.",
    "¿En qué escenario trabajas?": "Which stage do you work on?",
    "¿Seguro? Toca de nuevo para confirmar": "Sure? Tap again to confirm",
    "Úsala como app nativa": "Use it as a native app",
    "— Sin vincular —": "— Not linked —",
    "‹ Volver": "‹ Back",
    "↕ Cambios recibidos de otro técnico": "↕ Changes received from another engineer",
    "↩ Deshacer": "↩ Undo",
    "↩ Deshacer último cambio": "↩ Undo last change",
    "☀️ Modo claro": "☀️ Light mode",
    "✓ Guardar": "✓ Save",
    "✓ OK": "✓ OK",
    "🌙 Modo oscuro": "🌙 Dark mode",
    "📋 GUARDAR COMO PLANTILLA": "📋 SAVE AS TEMPLATE",
  },
  fr: {
    " · {n} deshacer disponibles": " · {n} annulation(s) possible(s)",
    "(sin nombre)": "(sans nom)",
    "+ AÑADIR GRUPO": "+ AJOUTER UN GROUPE",
    "+ AÑADIR NOTA": "+ AJOUTER UNE NOTE",
    "+ Añadir RF": "+ Ajouter RF",
    "+ Añadir artista": "+ Ajouter un artiste",
    "+ Añadir día": "+ Ajouter un jour",
    "+ Añadir fila": "+ Ajouter une ligne",
    "+ Añadir nota": "+ Ajouter une note",
    "+ Añadir stage": "+ Ajouter une scène",
    "+ CREAR FESTIVAL": "+ CRÉER UN FESTIVAL",
    "+ Campo": "+ Champ",
    "+ Nuevo campo": "+ Nouveau champ",
    ". Esta acción no se puede deshacer.": ". Cette action est irréversible.",
    "ARTISTA {n}": "ARTISTE {n}",
    "ARTISTAS": "ARTISTES",
    "Activar avisos": "Activer les alertes",
    "Android — Chrome": "Android — Chrome",
    "Archivo": "Fichier",
    "Asegúrate de haber ejecutado el SQL en Supabase y de tener las tablas": "Assurez-vous d'avoir exécuté le SQL dans Supabase et d'avoir les tables",
    "Avisos": "Alertes",
    "AÑADIR AL PLANO": "AJOUTER AU PLAN",
    "AÑADIR CONEXIÓN": "AJOUTER UNE CONNEXION",
    "AÑADIR ESCENARIO": "AJOUTER UNE SCÈNE",
    "AÑADIR FOH": "AJOUTER FOH",
    "AÑADIR MONITORES": "AJOUTER RETOURS",
    "Añadir": "Ajouter",
    "Añadir a pantalla de inicio": "Ajouter à l'écran d'accueil",
    "Añadir al Dock...": "Ajouter au Dock...",
    "Añadir al día": "Ajouter au jour",
    "Añadir día": "Ajouter un jour",
    "Añadir nota…": "Ajouter une note…",
    "Aún no hay miembros. Comparte un enlace para invitar.": "Aucun membre pour l'instant. Partagez un lien pour inviter.",
    "BANDAS": "GROUPES",
    "BORRAR": "SUPPRIMER",
    "Borrar": "Supprimer",
    "Borrar cuenta": "Supprimer le compte",
    "Borrar mi cuenta": "Supprimer mon compte",
    "Borrar mi cuenta y todos mis datos": "Supprimer mon compte et toutes mes données",
    "Borrando…": "Suppression…",
    "CAMPOS EXTRA": "CHAMPS SUPPL.",
    "CANTIDAD": "QUANTITÉ",
    "CH desde": "CH de",
    "CH hasta": "CH à",
    "COMPARTIR": "PARTAGER",
    "CONEXIÓN": "CONNEXION",
    "COPIA": "COPIE",
    "COPIADO": "COPIÉ",
    "COPIAR URL": "COPIER L'URL",
    "CORRIENTE": "ÉLECTRICITÉ",
    "CREAR GRUPO": "CRÉER LE GROUPE",
    "Campos extra": "Champs supplémentaires",
    "Campos extra (artista)": "Champs supplémentaires (artiste)",
    "Cancelar": "Annuler",
    "Cerrar": "Fermer",
    "Cerrar sesión": "Se déconnecter",
    "Colocar subbox": "Placer la subbox",
    "Compartir": "Partager",
    "Conectando…": "Connexion…",
    "Conexiones": "Connexions",
    "Conexión": "Connexion",
    "Consola": "Console",
    "Consola MON": "Console MON",
    "Continuar con Google": "Continuer avec Google",
    "Copiar": "Copier",
    "Copiar al día →": "Copier vers le jour →",
    "Copiar artistas": "Copier les artistes",
    "Corriente": "Électricité",
    "Crear festival": "Créer le festival",
    "Créalos primero en la pestaña": "Créez-les d'abord dans l'onglet",
    "DE": "DE",
    "DESCRIPCIÓN": "DESCRIPTION",
    "Desactivar avisos": "Désactiver les alertes",
    "Descripción · {d}": "Description · {d}",
    "Deshacer": "Annuler",
    "Dest": "Dest",
    "Duplicar grupo": "Dupliquer le groupe",
    "DÍA 1": "JOUR 1",
    "DÍA {n}": "JOUR {n}",
    "DÍAS": "JOURS",
    "DÍAS DESTINO": "JOURS CIBLES",
    "EDITAR ARTISTA": "MODIFIER L'ARTISTE",
    "EDITAR FESTIVAL": "MODIFIER LE FESTIVAL",
    "EDITAR GRUPO": "MODIFIER LE GROUPE",
    "EDITAR RULO": "MODIFIER LE CÂBLE",
    "EDITOR": "ÉDITEUR",
    "ESCENARIO": "SCÈNE",
    "ESCENARIO PRINCIPAL": "SCÈNE PRINCIPALE",
    "ETAPAS": "AMPLIS",
    "Editar": "Modifier",
    "Editor": "Éditeur",
    "Ej: El sábado mover a Cultura Jaén SL": "Ex : samedi déplacer vers Cultura Jaén SL",
    "Ej: HMA OPTOCORE Festival Box": "Ex : HMA OPTOCORE Festival Box",
    "Ej: Mad Cool 26": "Ex : Mad Cool 26",
    "Ej: Mad Cool 27": "Ex : Mad Cool 27",
    "Eliminar": "Supprimer",
    "Eliminar posición de escenario": "Supprimer la position de scène",
    "Error al conectar con la base de datos": "Erreur de connexion à la base de données",
    "Escenario": "Scène",
    "Escenario asignado": "Scène assignée",
    "Escribe una nota…": "Écris une note…",
    "Escribe {word} para confirmar": "Tapez {word} pour confirmer",
    "Esta acción es permanente e irreversible.": "Cette action est permanente et irréversible.",
    "Este navegador no soporta notificaciones push, o falta configurar la clave VAPID.": "Ce navigateur ne prend pas en charge les notifications push, ou la clé VAPID n'est pas configurée.",
    "Etiqueta": "Étiquette",
    "Etiqueta (RF, Backline…)": "Étiquette (RF, Backline…)",
    "Etiqueta (RF…)": "Étiquette (RF…)",
    "Etiqueta personalizada (opcional)": "Étiquette personnalisée (optionnel)",
    "Exportar PDF": "Exporter en PDF",
    "Exportar PDF del día": "Exporter le PDF du jour",
    "Expulsar": "Exclure",
    "FESTIVALES": "FESTIVALS",
    "FILAS · AMP — ID": "LIGNES · AMPLI — ID",
    "FONDO · BACKLINE": "FOND · BACKLINE",
    "Ficha compacta": "Fiche compacte",
    "Fila {r} · Col {c}": "Ligne {r} · Col {c}",
    "GRUPO VINCULADO": "GROUPE LIÉ",
    "GUARDAR CAMBIOS": "ENREGISTRER",
    "GUARDAR FESTIVAL": "ENREGISTRER LE FESTIVAL",
    "Generado:": "Généré :",
    "General": "Général",
    "Gestiona y sincroniza tus handovers de sonido en tiempo real con todo tu equipo.": "Gérez et synchronisez vos handovers son en temps réel avec toute votre équipe.",
    "Gestionar miembros": "Gérer les membres",
    "Gestión de consola y artistas": "Gestion de la console et des artistes",
    "Global:": "Global :",
    "Grupo": "Groupe",
    "Guardar": "Enregistrer",
    "Guardar artista": "Enregistrer l'artiste",
    "Guardar cambios": "Enregistrer",
    "HORARIOS": "HORAIRES",
    "HORARIOS — {d} · {n} artistas": "HORAIRES — {d} · {n} artistes",
    "Hecho": "Terminé",
    "INSTALAR APP": "INSTALLER L'APP",
    "Icono de instalación": "Icône d'installation",
    "Idioma": "Langue",
    "Inputs, corriente y plano": "Inputs, électricité et plan",
    "Instalar": "Installer",
    "Instrumento": "Instrument",
    "Instálala desde el navegador y ábrela como una app más, directamente desde tu pantalla de inicio.": "Installez-la depuis le navigateur et ouvrez-la comme une app, directement depuis votre écran d'accueil.",
    "Instálala desde el navegador y ábrela en su propia ventana, sin pestañas ni barra de direcciones.": "Installez-la depuis le navigateur et ouvrez-la dans sa propre fenêtre, sans onglets ni barre d'adresse.",
    "Mac — Safari": "Mac — Safari",
    "Menú": "Menu",
    "Mesa": "Console",
    "Mesa FOH": "Console FOH",
    "Mic / DI": "Mic / DI",
    "NOMBRE": "NOM",
    "NOMBRE DE LA PLANTILLA": "NOM DU MODÈLE",
    "NOMBRE DEL FESTIVAL": "NOM DU FESTIVAL",
    "NOMBRE DEL GRUPO": "NOM DU GROUPE",
    "NOTA (opcional)": "NOTE (optionnel)",
    "NOTAS": "NOTES",
    "NOTAS DEL DÍA": "NOTES DU JOUR",
    "NOTAS FOH (turno)": "NOTES FOH (service)",
    "NOTAS PREVIAS": "NOTES PRÉALABLES",
    "NUEVA POSICIÓN DE ESCENARIO": "NOUVELLE POSITION DE SCÈNE",
    "NUEVO ARTISTA": "NOUVEL ARTISTE",
    "NUEVO FESTIVAL": "NOUVEAU FESTIVAL",
    "NUEVO GRUPO": "NOUVEAU GROUPE",
    "NUEVO RULO": "NOUVEAU CÂBLE",
    "Name": "Nom",
    "No": "Non",
    "No hay artistas en este día": "Aucun artiste ce jour",
    "No hay grupos de corriente.": "Aucun groupe électrique.",
    "No se pudo actualizar la suscripción": "Impossible de mettre à jour l'abonnement",
    "No se pudo borrar la cuenta": "Impossible de supprimer le compte",
    "Nombre (ej. SB1)": "Nom (ex. SB1)",
    "Nombre / Fuente": "Nom / Source",
    "Nombre artista": "Nom de l'artiste",
    "Nombre artista *": "Nom de l'artiste *",
    "Nombre del stage": "Nom de la scène",
    "Nota para tu compañero…": "Note pour ton collègue…",
    "Notas": "Notes",
    "Notas FOH": "Notes FOH",
    "Notas previas": "Notes préalables",
    "Nueva posición de monitores": "Nouvelle position de retours",
    "Otro": "Autre",
    "Owner": "Propriétaire",
    "PARA": "VERS",
    "PLANO": "PLAN",
    "POSICIONES": "POSITIONS",
    "POSICIÓN EN ESCENARIO": "POSITION SUR SCÈNE",
    "Parcheo FOH": "Patch FOH",
    "Plantillas": "Modèles",
    "Preset": "Preset",
    "Pulsa": "Appuie sur",
    "PÚBLICO": "PUBLIC",
    "RF — {n} unidades": "RF — {n} unités",
    "RULOS": "CÂBLES",
    "Recibe notificaciones de los artistas del escenario en el que estés trabajando.": "Recevez des notifications pour les artistes de la scène sur laquelle vous travaillez.",
    "Rulo permanente": "Câble permanent",
    "Rutas": "Routes",
    "SC FIN": "SC FIN",
    "SC INICIO": "SC DÉBUT",
    "SH FIN": "SH FIN",
    "SH INICIO": "SH DÉBUT",
    "SHOW FIN": "SHOW FIN",
    "SHOW INICIO": "SHOW DÉBUT",
    "SIN CONEXIÓN — mostrando últimos datos guardados": "HORS LIGNE — affichage des dernières données enregistrées",
    "SOUNDCHECK": "BALANCE",
    "STAGES": "SCÈNES",
    "Se borrarán para siempre:": "Seront supprimés définitivement :",
    "Se borrarán todos los inputs, grupos de corriente y el plano de {n}. Esta acción no se puede deshacer.": "Tous les inputs, groupes électriques et le plan de {n} seront supprimés. Cette action est irréversible.",
    "Selecciona los artistas a copiar y los días destino.": "Sélectionnez les artistes à copier et les jours cibles.",
    "Setup monitor": "Config. retours",
    "Setup técnico": "Config. technique",
    "Señal": "Signal",
    "Ningún artista tiene soundcheck asignado": "Aucun artiste n'a de balance assignée",
    "Sin artistas en este día": "Aucun artiste ce jour",
    "Sin confirmar": "Non confirmé",
    "Sin descripción": "Sans description",
    "Sin días configurados": "Aucun jour configuré",
    "Sin grupos de etapas": "Aucun groupe d'amplis",
    "Sin inputs en este rango — defínelos en la pestaña INPUTS.": "Aucun input dans cette plage — définissez-les dans l'onglet INPUTS.",
    "Sin notas para este día": "Aucune note pour ce jour",
    "Slots en directo": "Slots en direct",
    "Subbox": "Subbox",
    "Sí, borrar": "Oui, supprimer",
    "Sí, eliminar": "Oui, supprimer",
    "TIPO DE CABLE": "TYPE DE CÂBLE",
    "TUS": "VOS",
    "Te invito a {n} como {r}": "Je t'invite à {n} en tant que {r}",
    "Tipo": "Type",
    "Todos los escenarios": "Toutes les scènes",
    "Tomas": "Prises",
    "Tomas {n}": "Prises {n}",
    "Tus avisos de soundcheck se ajustarán a este escenario. Puedes cambiarlo cuando quieras.": "Vos alertes de balance s'adapteront à cette scène. Vous pouvez la changer à tout moment.",
    "Tus festivales y todos sus datos": "Vos festivals et toutes leurs données",
    "Tu pertenencia a festivales de otros": "Votre participation aux festivals d'autres",
    "Tus preferencias y avisos": "Vos préférences et alertes",
    "Tu cuenta de acceso": "Votre compte d'accès",
    "Type": "Type",
    "Técnico": "Technicien",
    "USAR PLANTILLA": "UTILISER LE MODÈLE",
    "Usar": "Utiliser",
    "Usar global ↩": "Utiliser global ↩",
    "User / artista": "User / artiste",
    "Usuario {x}": "Utilisateur {x}",
    "VISOR": "LECTEUR",
    "Valor": "Valeur",
    "Vas a borrar": "Vous allez supprimer",
    "Vincula un grupo de la pestaña CORRIENTE.": "Liez un groupe depuis l'onglet ÉLECTRICITÉ.",
    "Visible en todos los días del stage": "Visible tous les jours de la scène",
    "Visor": "Lecteur",
    "Windows / Mac — Chrome": "Windows / Mac — Chrome",
    "a la derecha de la barra de direcciones": "à droite de la barre d'adresse",
    "arriba a la derecha": "en haut à droite",
    "cargando…": "chargement…",
    "claro": "clair",
    "consola mon": "console mon",
    "creadas.": "créées.",
    "en la barra inferior": "dans la barre du bas",
    "en la barra superior": "dans la barre du haut",
    "este día": "ce jour",
    "iPhone / iPad — Safari": "iPhone / iPad — Safari",
    "mesa": "console",
    "oscuro": "sombre",
    "preset?": "preset ?",
    "sin confirmar": "non confirmé",
    "sin entradas": "aucune entrée",
    "técnico": "technicien",
    "y": "et",
    "{a} artistas · {d} días": "{a} artistes · {d} jours",
    "{d} días · {a} artistas": "{d} jours · {a} artistes",
    "{i} inputs · {p} grupos corriente": "{i} inputs · {p} groupes électriques",
    "{n} INPUT(S) EN RANGO": "{n} INPUT(S) DANS LA PLAGE",
    "{n} art.": "{n} art.",
    "{n} artistas": "{n} artistes",
    "{n} entradas · últimos 1000 cambios": "{n} entrées · 1000 derniers changements",
    "{n} filas": "{n} lignes",
    "{n} input(s) de la pestaña INPUTS en este rango": "{n} input(s) de l'onglet INPUTS dans cette plage",
    "{n} tomas": "{n} prises",
    "{s} stages · {a} artistas": "{s} scènes · {a} artistes",
    "¡ENTENDIDO!": "COMPRIS !",
    "¿Borrar artista?": "Supprimer l'artiste ?",
    "¿Borrar esta conexión?": "Supprimer cette connexion ?",
    "¿Borrar festival?": "Supprimer le festival ?",
    "¿Borrar plantilla?": "Supprimer le modèle ?",
    "¿Con qué acceso?": "Avec quel accès ?",
    "¿Eliminar el grupo \"{n}\"?": "Supprimer le groupe « {n} » ?",
    "¿Eliminar el stage \"{n}\"? Se perderán todos sus días y artistas.": "Supprimer la scène « {n} » ? Tous ses jours et artistes seront perdus.",
    "¿Eliminar la posición \"{n}\"?": "Supprimer la position « {n} » ?",
    "¿Eliminar la posición de escenario?": "Supprimer la position de scène ?",
    "¿Eliminar posición de monitores \"{n}\"?": "Supprimer la position de retours « {n} » ?",
    "¿Eliminar todos los artistas de FOH en {n}?": "Supprimer tous les artistes FOH de {n} ?",
    "¿Eliminar {d}? Se perderán todos sus artistas.": "Supprimer {d} ? Tous ses artistes seront perdus.",
    "¿En qué escenario trabajas?": "Sur quelle scène travailles-tu ?",
    "¿Seguro? Toca de nuevo para confirmar": "Sûr ? Appuyez de nouveau pour confirmer",
    "Úsala como app nativa": "Utilisez-la comme une app native",
    "— Sin vincular —": "— Non lié —",
    "‹ Volver": "‹ Retour",
    "↕ Cambios recibidos de otro técnico": "↕ Modifications reçues d'un autre technicien",
    "↩ Deshacer": "↩ Annuler",
    "↩ Deshacer último cambio": "↩ Annuler le dernier changement",
    "☀️ Modo claro": "☀️ Mode clair",
    "✓ Guardar": "✓ Enregistrer",
    "✓ OK": "✓ OK",
    "🌙 Modo oscuro": "🌙 Mode sombre",
    "📋 GUARDAR COMO PLANTILLA": "📋 ENREGISTRER COMME MODÈLE",
  },
};
